#!/usr/bin/env python3
"""W3.0 — the PREDETERMINED full-criterion efficiency surface (prediction for G1).

WP2 froze a full-criterion *marginal* (0.79, at μ=0.5, oracle windows) and a
*copy-criterion* (μ, S/N) surface — but not a full-criterion, END-TO-END surface.
G1 ("recovery agrees with predicted efficiency") needs exactly that: the recovery
probability the frozen pipeline assigns to an injected copy at (μ, host S/N),
Tier-1 triage included, so it is comparable to the blind evaluation.

This regenerates it on the DEVELOPMENT split (already used in design — no test-set
contact) by injecting achromatic copies over the frozen grid and running the SAME
`run_frozen_chain` the blind evaluator uses. The result, `wp3_predicted_efficiency
.parquet`, is committed as the prediction BEFORE the hidden set is scored. It is a
prediction-generation step (frozen pipeline, zero new thresholds), not a new
analysis version.

NB: because this is end-to-end (Tier-1 included), the marginal here may be <= the
WP2 0.79 tier2-only oracle figure; that is expected and is the honest prediction.

W3b.7-C — TWO VERSIONS. Under v1 the prediction is generated by injecting fresh
copies and running `run_frozen_chain` (`build`, below). Under v2 that would predict
the WRONG THING: G1 would compare observed-v2 recovery against a v1 prediction and
mis-fire, a repeat of round 1's metric failure in a new place.

So under v2 the prediction is a TRANSFORM over the dev null ensemble
(`build_v2`): its `injection` family already holds thousands of achromatic copies
scored by the same chain the evaluator runs, so applying the committed calibration
to them yields the v2 recovery prediction directly — a broader base than a fresh
campaign, and guaranteed consistent with the evaluator by construction.

Both paths emit the SAME schema (tns_name, dt_bins, mu, recovered, host_snr, …) so
`unblind.g1_assess` is version-agnostic.
"""
from __future__ import annotations

import argparse
import os

import numpy as np
import pandas as pd
import yaml

from .. import tierb_io
from ..adverse import generators as gen
from ..injection import efficiency as eff
from ..margin import calibrate as mcal
from ..tier1 import profile
from . import foundation
from .pipeline import run_frozen_chain


def build(dev_hosts, tbdir, ana_cfg, dt_bins, mu_grid, n_hosts, log_every=25):
    grid = [(dt, mu) for dt in dt_bins for mu in mu_grid]
    rows, used = [], 0
    for tns in dev_hosts.tns_name:
        if used >= n_hosts:
            break
        path = os.path.join(tbdir, f"{tns}_tierb.h5")
        if not os.path.exists(path):
            continue
        tb = tierb_io.load_tier_b(path)
        if tb["noise_failed"]:
            continue
        nt = tb["standardized"].shape[1]
        c = int(np.argmax(profile.build_profile(tb)["I"]))
        hp = dev_hosts[dev_hosts.tns_name == tns].iloc[0]
        used += 1
        for dt, mu in grid:
            if c + dt >= nt - 5 or c - 5 < 0:
                continue
            tb2 = gen.inject(tb, c, dt, mu, "achromatic_copy", None)
            d = run_frozen_chain(tb2, ana_cfg)
            rows.append(dict(tns_name=tns, dt_bins=dt, mu=mu,
                             recovered=bool(d["is_candidate"]),
                             copy_ok=bool(d["copy_ok_any"]),
                             delta_chi2=d["best_delta_chi2"], ncc=d["best_ncc"],
                             reduced_chi2=d["best_reduced_chi2"],
                             n_pass=d["best_n_pass"],
                             host_snr=float(hp.catalog_snr),
                             host_width_s=float(hp.burst_width_s),
                             host_bandwidth_mhz=float(hp.usable_bandwidth_mhz)))
        if used % log_every == 0:
            print(f"[predict] {used}/{n_hosts} hosts, {len(rows)} injections", flush=True)
    return pd.DataFrame(rows)


def build_v2(ensemble, calib, ana_cfg, man):
    """v2 prediction: apply the committed calibration to the dev injection family.

    `host_snr` is the manifest `catalog_snr`, NOT the spectrum-derived `peak_snr`
    the calibration conditions on — the sealed labels carry `catalog_snr`, so this
    keeps the predicted and observed sides of G1 on the same axis. (Conditioning
    still uses peak_snr internally; the two are different jobs.)
    """
    alpha = float(ana_cfg["margin"]["alpha"])
    inj = ensemble[(ensemble.get("truth_class") == "positive")
                   & (ensemble.family == "injection")].copy()
    if "error" in inj:
        inj = inj[inj.error == ""]
    assert len(inj), "the ensemble carries no `injection` family to predict from"

    p = calib.apply(inj)
    inj["p_robust"] = p.p_robust.to_numpy()
    inj["recovered"] = (inj.M > 0) & (inj.p_robust <= alpha)

    mcols = ["tns_name", "catalog_snr", "burst_width_s", "usable_bandwidth_mhz"]
    inj = inj.merge(man[mcols], on="tns_name", how="left")
    return pd.DataFrame(dict(
        tns_name=inj.tns_name, dt_bins=inj.dt_bins, mu=inj.mu,
        recovered=inj.recovered.astype(bool),
        copy_ok=(inj.M > -np.inf),
        M=inj.M, p_robust=inj.p_robust,
        delta_chi2=inj.best_delta_chi2, ncc=inj.best_ncc,
        reduced_chi2=inj.best_reduced_chi2, n_pass=inj.best_n_pass,
        host_snr=inj.catalog_snr.astype(float),
        host_width_s=inj.burst_width_s.astype(float),
        host_bandwidth_mhz=inj.usable_bandwidth_mhz.astype(float)))


def snr_quartiles(host_snr):
    """S/N quartile labels, robust to few distinct values (drops empty edges)."""
    binned = pd.qcut(host_snr, 4, duplicates="drop")
    codes = binned.cat.codes                              # 0..(nbins-1), ordered low->high
    return codes.map(lambda c: f"Q{c + 1}" if c >= 0 else "NA")


def surface(df):
    """Full-criterion ε(μ, host S/N quartile) with Wilson CIs (the prediction)."""
    df = df.copy()
    df["host_snr_bin"] = snr_quartiles(df.host_snr)
    g = df.groupby(["mu", "host_snr_bin"]).recovered.agg(["sum", "count"]).reset_index()
    g["efficiency"] = g["sum"] / g["count"]
    ci = g.apply(lambda r: eff.wilson(int(r["sum"]), int(r["count"])), axis=1,
                 result_type="expand")
    g["ci_lo"], g["ci_hi"] = ci[1].round(4), ci[2].round(4)
    return df, g.rename(columns={"sum": "recovered", "count": "n"})


def main():
    ap = argparse.ArgumentParser(description="W3.0 — predicted efficiency surface (dev)")
    ap.add_argument("--wp3-config", help="omit only until the v2 harness config "
                                         "exists (W3b.7-F); the freeze contract is "
                                         "then NOT asserted")
    ap.add_argument("--analysis-config", required=True)
    ap.add_argument("--repo-root", default=".")
    ap.add_argument("--split", required=True)
    ap.add_argument("--manifests", required=True)
    ap.add_argument("--tier-b-dir")
    ap.add_argument("--out", required=True)
    ap.add_argument("--n-hosts", type=int, default=150)
    ap.add_argument("--ensemble", help="v2: dev null ensemble to transform")
    ap.add_argument("--calibration", help="v2: committed calibration dir")
    a = ap.parse_args()

    if a.wp3_config:
        wp3 = foundation.load_wp3_config(a.wp3_config)
        foundation.assert_freeze_contract(wp3, os.path.expanduser(a.repo_root))
    else:
        print("[predict] WARNING: no --wp3-config; freeze contract NOT asserted")
    ana = yaml.safe_load(open(a.analysis_config))
    v2 = bool(ana.get("margin"))

    split = pd.read_parquet(os.path.expanduser(a.split))
    man = pd.read_parquet(os.path.join(os.path.expanduser(a.manifests),
                                       "observation_manifest.parquet"))

    if v2:
        assert a.ensemble and a.calibration, (
            "the v2 prediction is a transform over the dev null ensemble: "
            "--ensemble and --calibration are both required")
        calib = mcal.load_calibration(a.calibration)
        ens = pd.read_parquet(os.path.expanduser(a.ensemble))
        df = build_v2(ens, calib, ana, man)
        print(f"[predict] v2 ({ana['analysis_version']}, alpha="
              f"{ana['margin']['alpha']}): transformed {len(df)} dev injections")
    else:
        mcols = ["tns_name", "catalog_snr", "burst_width_s", "usable_bandwidth_mhz",
                 "n_subbursts"]
        single = man[mcols][man.n_subbursts.fillna(1) <= 1]
        dev = split[(split.split == "development") & (~split.quarantined)] \
            .merge(single, on="tns_name")
        inj = ana["injection"]
        df = build(dev, os.path.expanduser(a.tier_b_dir), ana,
                   inj["dt_bins"], inj["mu"], a.n_hosts)
    df, surf = surface(df)

    outp = os.path.expanduser(a.out)
    os.makedirs(os.path.dirname(os.path.abspath(outp)), exist_ok=True)
    df.to_parquet(outp, index=False)
    surf.to_parquet(outp.replace(".parquet", "_surface.parquet"), index=False)

    print(f"[predict] {len(df)} dev injections -> {outp}")
    if v2:
        # cross-check (docs/WP3b_W3b.7_plan.md §C): this transform and the
        # operating-curve script must agree, or one of them is wrong
        bright = df[df.mu >= 0.5]
        print(f"[predict] CROSS-CHECK marginal={df.recovered.mean():.4f} "
              f"mu>=0.5={bright.recovered.mean():.4f} "
              f"— must match the dev operating curve at this alpha")
    print("\nPredicted full-criterion efficiency by μ:")
    # use_flag_column: under v2 `recovered` IS the decision (M>0 AND p<=alpha);
    # recomputing it from the copy criterion would overstate efficiency badly
    print(eff.efficiency_by(df, "mu", use_flag_column=v2).to_string(index=False))
    print(f"\nMarginal predicted efficiency: {df.recovered.mean():.3f} "
          f"(n={len(df)})")
    print("\nε(μ, host S/N) surface:")
    print(surf.pivot(index="mu", columns="host_snr_bin", values="efficiency")
          .round(2).to_string())


if __name__ == "__main__":
    main()
