#!/usr/bin/env python3
"""W3b.7-G — DRESS REHEARSAL: run the whole round-2 chain on a DECOY set.

The controller -> evaluator -> unblind chain has never been run under v2. Finding a
plumbing bug against the sealed pool would burn the last remaining draw on a
missing column or a bad path. So run the complete chain first on a decoy round
drawn from DEVELOPMENT sources, which are already fully used in design: it costs
nothing and reveals nothing.

  ##########################################################################
  #  THIS VALIDATES THE MACHINERY, NOT THE SCIENCE.                        #
  #  Dev is the calibration set, so the decoy's false-positive rates are   #
  #  optimistic by construction. Nothing here is evidence about v2's       #
  #  out-of-sample behaviour — that is what pool 1 is for.                 #
  ##########################################################################

The harness config is GENERATED here, into the output dir, pinned to whatever the
v2 analysis config currently hashes to. That keeps the rehearsal self-consistent
without pre-committing a hash that is still moving, and makes it structurally
impossible to mistake the generated file for the signed round-2 harness (it says
`split_source: development` and `REHEARSAL` in its own header).

  PYTHONPATH=src .venv/bin/python scripts/wp3b_rehearsal.py \
      --repo-root . --out-dir ~/frb_catalog2_prep/wp3b/rehearsal --seed 20260725
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys

import yaml

from echo_frb.search.margin import calibrate as mcal

PY = sys.executable
V2_ANA = "config/wp2_analysis_config_v2.yaml"
V2_WP3 = "config/wp3_blind_config_v2.yaml"


def run(step, args, env):
    print(f"\n=== [rehearsal] {step} ===", flush=True)
    r = subprocess.run([PY, "-m"] + args, env=env)
    if r.returncode:
        raise SystemExit(f"[rehearsal] STEP FAILED: {step} (exit {r.returncode})\n"
                         f"Fix this before pool 1 is touched — that is the point "
                         f"of the rehearsal.")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", default=".")
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--seed", type=int, required=True)
    ap.add_argument("--calibration", default="~/frb_catalog2_prep/wp3b/calibration_v2")
    ap.add_argument("--prep", default="~/frb_catalog2_prep")
    ap.add_argument("--workers", type=int, default=24)
    ap.add_argument("--full", action="store_true",
                    help="use the real round-2 mixture (600 items, ~5GB of decoy h5)")
    a = ap.parse_args()

    repo = os.path.abspath(os.path.expanduser(a.repo_root))
    out = os.path.expanduser(a.out_dir)
    prep = os.path.expanduser(a.prep)
    calib = os.path.expanduser(a.calibration)
    os.makedirs(out, exist_ok=True)
    env = dict(os.environ, PYTHONPATH=os.path.join(repo, "src"))

    # --- generate the decoy harness, pinned to the CURRENT v2 hash ----------
    cfg = yaml.safe_load(open(os.path.join(repo, V2_WP3)))
    ana_hash = mcal.sha256_file(os.path.join(repo, V2_ANA))[:16]
    calib_hash = mcal.sha256_file(os.path.join(calib, mcal.MANIFEST_FILE))
    cfg["wp3_version"] = "wp3-REHEARSAL-not-a-round"
    cfg["frozen"]["analysis_config_sha16"] = ana_hash
    cfg["frozen"]["calibration_manifest_sha256"] = calib_hash
    cfg["pools"]["split_source"] = "development"          # <-- DECOY, not the test split
    if not a.full:
        cfg["mixture"].update(n_injections=60, n_real_null=60, n_per_adverse_kind=15)
    cfg["_rehearsal"] = ("Generated by scripts/wp3b_rehearsal.py. Draws from "
                         "DEVELOPMENT sources. NOT the signed round-2 harness.")
    hpath = os.path.join(out, "rehearsal_harness.yaml")
    yaml.safe_dump(cfg, open(hpath, "w"), sort_keys=False)

    print(__doc__.split("  PYTHONPATH")[0])
    print(f"[rehearsal] v2 analysis hash {ana_hash} · calibration {calib_hash[:16]}…")
    print(f"[rehearsal] decoy mixture: {cfg['mixture']['n_real_null']} real / "
          f"{cfg['mixture']['n_injections']} inj / "
          f"{cfg['mixture']['n_per_adverse_kind']}x7 adverse")

    pools = os.path.join(out, "rehearsal_pools.parquet")
    round_dir = os.path.join(out, "round")

    run("W3.0 pools (development sources)", [
        "echo_frb.search.blind.foundation", "--wp3-config", hpath,
        "--repo-root", repo, "--split", f"{prep}/wp2/source_split.parquet",
        "--out", pools], env)

    run("W3.1 controller (sealed seed, decoy mixture)", [
        "echo_frb.search.blind.controller", "--wp3-config", hpath,
        "--analysis-config", os.path.join(repo, V2_ANA), "--repo-root", repo,
        "--pools", pools, "--manifests", f"{prep}/manifests",
        "--tier-b-dir", f"{prep}/tier_b_standardized", "--out-dir", round_dir,
        "--round", "2", "--seed", str(a.seed)], env)

    run("W3.2 blind evaluator (v2: margin chain + committed calibration)", [
        "echo_frb.search.blind.evaluate", "--wp3-config", hpath,
        "--analysis-config", os.path.join(repo, V2_ANA), "--repo-root", repo,
        "--round-dir", round_dir, "--calibration", calib,
        "--workers", str(a.workers)], env)

    run("W3.3 unblind + gate arithmetic", [
        "echo_frb.search.blind.unblind", "--wp3-config", hpath,
        "--repo-root", repo, "--round-dir", round_dir,
        "--predicted", f"{prep}/wp3b/wp3b_predicted_efficiency.parquet",
        "--out-dir", os.path.join(out, "validation")], env)

    # --- what the rehearsal must demonstrate --------------------------------
    summary = json.load(open(os.path.join(out, "validation",
                                          "blind_validation_summary.json")))
    import pandas as pd
    scores = pd.read_parquet(os.path.join(round_dir, "hidden_scores.parquet"))
    missing = [c for c in ("M", "p_robust", "worst_family", "is_candidate")
               if c not in scores.columns]
    assert not missing, f"v2 scores are missing {missing} — the evaluator ran v1"
    assert (scores.error == "").all(), \
        f"{int((scores.error != '').sum())} items errored: " \
        f"{scores[scores.error != ''].error.value_counts().head().to_dict()}"

    print("\n" + "#" * 74)
    print("#  REHEARSAL COMPLETE — MACHINERY ONLY, NOT A RESULT".ljust(73) + "#")
    print("#  Dev is the calibration set: these FP rates are optimistic by".ljust(73) + "#")
    print("#  construction and are NOT evidence about v2. Pool 1 is the test.".ljust(73) + "#")
    print("#" * 74)
    print(f"chain verdict (meaningless, but it must COMPUTE): {summary['verdict']}")
    print(f"items scored: {len(scores)}  ·  flagged: {int(scores.is_candidate.sum())}  "
          f"·  errors: 0")
    print(f"p_robust populated: {int(scores.p_robust.notna().sum())}/{len(scores)}")
    print(f"-> {out}")
    print("\nEvery step ran. Remaining before W3b.8: the PI's signature on "
          "docs/WP3b_preregistration_addendum.md and a git commit of the configs "
          "+ calibration commitment.")


if __name__ == "__main__":
    main()
